# Generated by Django 5.1.1 on 2024-12-07 01:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_profile_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=50), blank=True, size=None),
        ),
    ]
