# Generated by Django 5.1.1 on 2024-12-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='language_tw',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_tw',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
