# Generated by Django 5.1.1 on 2024-12-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='sub_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
