# Generated by Django 5.1.1 on 2024-12-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_values_sub_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Values',
        ),
    ]
