# Generated by Django 5.1.1 on 2024-12-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_values'),
    ]

    operations = [
        migrations.DeleteModel(
            name='languages',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
    ]
