# Generated by Django 5.1.1 on 2024-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_mission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
