# Generated by Django 5.1.1 on 2024-12-02 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_mission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='detail',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='mission',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='salary_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
