# Generated by Django 5.1.1 on 2024-12-02 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_mission_currency_alter_mission_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='sponsor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='currency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='detail',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='mission',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='salary',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='salary_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
