# Generated by Django 5.1.1 on 2024-12-06 11:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_remove_mission_sponsor_mission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='mission',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True), blank=True, size=None),
        ),
    ]
