# Generated by Django 5.1.1 on 2024-12-07 01:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0010_alter_mission_languages_alter_mission_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=50), blank=True, size=None),
        ),
    ]
